# -*- coding: utf-8 -*-
"""Python Learning-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmSWo5TZy0apTxIGDqLjm2DwuzRTqOa3
"""

# Print Function

print("Hello world!!")

x=input()

print(x)

print(type(x))

y=input()

print(y)

print(type(y))

z=int(1234)

print(z)

print(type(z))

print("nikss")

print("Nikss","Kimtan",1,2,3)

print("Nikss",10,20,30,40,50, sep="__")
print("Jadu",20)

print("Nikss",10,20, sep="\n")

print("Nikss",10 ,end="  ")
print("Jadu",20)

print("Nikss",10,sep="\n" ,end="--->")
print("Jadu",20,sep="***")

# Pyhton Operetors
# Arithematic Operators !!!!

# 1) Addition

a = 5
 b = 3

print(a+b)

a-b

a/b

a*b

a//b

a%b

a

print(a**b)

1.5+1

# String cancatination

first="Nikita"
last="Jadhav"

print(first+last)

#string mutiplicaton

first*3

# Modulus Operator
# consider Remender

print(a/b)
print(a%b)

# floor division---->to the nearest smaller integer

print(a//b)

# power accepts two values base the power

print(a**b)
print(2**3)

# Comparison Operators
# (==,!=,<,>,<=,>=)

a=10
b=20

print(a==b)
print(a!=b)
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)

# Assignment Operators

a=5
a=a+3
print(a)

a+=3
print(a)

a-=3
print(a)

a/=3
print(a)

a*=3
print(a)

# Logical Operator
# (and,or,not)

#AND
 #   i/p 1        i/p 2         o/p
    #  T           T             T
    #  T           F             F
    #  F           T             F
    #  F           F             F

print(True and True)
print(True and False)
print(False and True)
print(False and False)

# OR
 #   i/p 1        i/p 2         o/p
    #  T           T             T
    #  T           F             T
    #  F           T             T
    #  F           F             F

print(True or True)
print(True or False)
print(False or True)
print(False or False)

3>2 or 5<9

# NOT
 #   i/p 1        o/p
    #  T           F
    #  F           T

not 2>3

# Special Operatorss
# in and is (Membership operators)

name="Nikita Jadhav"
print("N" in name)
print("z"in name)
print("Nikita" in name)

a=5
b=5
print(id(a),id(b))
a is b

# Control Flow Statement
#   1) If and Else condition  (Syntax)

age=int(input())
if age>18:
  print("You can drive you are eligible")
  print("Drive slowly")
else:
  print("You can't Drive Just wait still you turen 18  !!!")

#   2)  Neasted If and Else   (Syntax)

age=int(input())
if age>18:
  if age>=65:
    print("Take rest")
  else:
    print("you are eligible")
    print("Drive slow")
else:
  print("Just wait still you turen 18  !!!")

#   3)  If and Else  repetation  (Syntax)

num=int(input())
if num>0:
  print("Positve Number")
if num<0:
  print("Negative Number")
else:
  print("Zero")

#   4)  if and Elif   (Syntax)

num=int(input())
if num>0:
  print("Positve Number")
elif num<0:
  print("Negative Number")
else:
  print("Zero")

# Challenge (1) Print Largest

#  Que-1--->Find maximum in list
    # Given marks of student in a class. find topper of the class

marks=[90,30,100,50,80,95]

#iterate on the list


highest=marks[0]
for i in marks:
  #check the condition
  if i>highest:
    highest=i

print(highest)

max(marks)

min(marks)

# Challenge (2) Grading System

# A: equal and above 90
# B: equal to 80 and less than 90
# C: equal to 70 and less than 80
# D: equal to 60 and less than 70
# E: less than 60


marks=int(input())
if marks>=90 and marks<=100:
  print("A Grade")
elif marks>=80 and marks<=90:
  print("B Grade")
elif marks>=70 and marks<=80:
  print("C Grade")
elif marks>=60 and marks<=70:
  print("D Grade")
elif marks<60:
  print("E Grade")
else:
  print("Invalid")

# LOOPS
# Its is nothing but repeatation of same work---> if i want to print same line for multiple times then loop is used...

                          #Enter the while loop
                                   #|
                                   #|
                                  #\ /     #False
       #----------------- #Test Condition------------
      #|                           #|               |
      #|                           #| #True         |
      #|                           #|               |------Exit the while loop
       #------------------- While loop body

# Initiliaing value
# loop condition
# Updating value


#initializaion

i=1
 #Loop condition

while i <=6:
  # inside body
  print("You are the best !!")

  #upadate
  i +=1

# print all numbers from 1 to 10 using loop

i=1
while i<=10:
  print(i , end=" ")   # for single line end i s as a space
  i+=1

# print all numbers from 0 to 10 using loop

i=0
while i<=10:
  print(i)
  i+=1

i=0
while i<=10:
  if i % 2==0:
    print(i)
  i+=1

# print SUM of all numbers from 1 to 10 using loop

i=1
add=0
while i <= 10:
  add+=i
  print(add)
  i+=1
# print(add)

# print SUM of all  even numbers from 1 to 10 using loop
i=1
add=0
while i<=10:
  if i%2==0:
    add+=i
    i+=1
    print(add)

# Range Function
  # range() function allows users to series of numbers
  # it is iterable as well

# Syntaxx

# range(start , end, jump)
 # S---> form where you start
 # E---> at where you want to end
 # J---> gapping

range(10)   # bydefault jump is 1
list(range(1, 5))
# here 1 is starting  and 5 is end whish is excluded

# Jump
list(range(1,10,2))

list(range(10,1,1))

# Negative jump

list(range(10,1,-1))

list(range(10,0,-2))

#--------------Iterator,Iterable and iteration-------------#
 # chocolate distribution of your bday  so in this
  #Iterator---> you
  #Iterable---> whole class
  #Iteration---> All process

#For Loop

for i in range (1,11):
  print(i)

# print Multiplication table of 5

n=int(input())
for i in range(1,11):
  print(i*n)

# Print pattern 1

   # # # #
   # # # #
   # # # #
   # # # #



for i in range(4):
  print("#", end=" ")
print()
for i in range(4):
  print("#", end=" ")
print()
for i in range(4):
  print("#", end=" ")
print()
for i in range(4):
  print("#", end=" ")
print()

for i in range(4):
  for j in range(4):
    print("#",end=" ")
  print()

# pattern No. 2

#
# #
# # #
# # # #
# # # # #

n=int(input())
 # run for rows
for i in range(1,n+1) :
  for j in range(i):
    print("#",end=" ")
  print()

n=int(input())
for i in range(1,n+1):
  for j in range(i+1):
    print("#",end=" ")
  print()

#---------Break,Continue and pass------------#
# Pass

for i in range(1,10):
  pass            # this used when you don't know the code and still want to sun without error

# continue
for i in range(1,10):
 if i ==5:
     continue     # it skip perticular part process further
 print(i)

# Break
for i in range(1,10):
  if i==5:
    break    # whenever condition is satisfied  is break further task
  print(i)

#-------String--------#
#-->sequence of characters--->alphabets capital or small , Digits(1-9) , special charcter (@ ,#,$,%....)
# Define using single double and tripple quotes as well

"Nikita" == "atikin"
a="Nikita"
print(a)
print(type(a))

# Ord